print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')

print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')
print('Good Afternoon!')

print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')
print('Good Night!')

print('Hong Gil Dong')
print('20살')
print('Korea Seoul')
print('010-1234-5678')
print('virtue14.dev@gmail.com')

print('Python Study!')
print('도서 구입 : 20,000원')
print('외식 : 10,000원')

print('Pyton Study!')
print('Hello World!')